### ISSUE TITLE
优化代码的可读性

### ISSUE THREAD

**Issue by copi143** [CLimber-Rong/stamon#1]
## 使用 100 或 120 的列数

过小的列数限制会导致大量语句写在多行内，降低了代码的可读性<br>
同时 namespace xxx 内建议不要缩进留出更多列给代码<br>

## 不要用嵌套的方式书写内层 namespace

```cpp
namespace stamon {
	namespace vm {
```

改为

```cpp
namespace stamon::vm {
```

## 在 namespace 的末尾加上注释

```cpp
namespace stamon {
} // namespace stamon
```

## 将宏用 `do {} while(0)` 包裹，同时在宏后加上分号，如

```cpp
#define WRITE(b) \
	writer.write(b);\
	CATCH {\
		ErrorMsg->add(ex->getError());\
		return;\
	}

WRITE(0xAB)
```

修改为

```cpp
#define WRITE(b) \
	do {\
		writer.write(b);\
		CATCH {\
			ErrorMsg->add(ex->getError());\
			return;\
		}\
	} while(0)

WRITE(0xAB);
```

## 少用宏

- `#define WRITE(b)` 建议改为函数调用
- `#define STAMON_VER_X 2` 建议改为常量表达式

## 不要在头文件中且在上层namespace中using下层namespace

```cpp
namespace stamon {
	using namespace stamon::ir;
	using namespace stamon::datatype;
	using namespace stamon::c;
	using namespace stamon::vm;
	using namespace stamon::sfn;
}
```

这样把 `stamon` 分为 `ir` `datatype` 等就没有了意义

## 不要用 `#ifndef` `#define` 来防止头文件被重复包含

现代编译器应当都支持 `#pragma once`

## 不要将变量、函数放在根空间

既然已经有了 `namespace stamon` 请将变量、函数放在这之中，即使它不会被导出

**Comment by copi143** [comment]
## 建议使用 `clang-format` 和 `clang-tidy`

附上我的配置，虽然不一定适合你

[.clang-format](https://github.com/user-attachments/files/15858726/clang-format.txt)
[.clang-tidy](https://github.com/user-attachments/files/15858725/clang-tidy.txt)

重命名为 `.clang-format` 和 `.clang-tidy`，放到项目根目录中，配置文件为 yaml 格式

** 注意我设置的格式化风格和你代码的风格有很大的不同 **

**Comment by CLimber-Rong** [comment]
感谢提议！我对代码的风格进行了如下调整：

1. 将嵌套的namespace整合成一个namespace
2. 在 namespace 的末尾加上注释
3. 不在头文件中且在上层namespace中using下层namespace
4. 将一些能放入namespace的常量值放入了namespace里
5. 不要用 #ifndef #define 来防止头文件被重复包含，而是使用#pragma once

与此同时，我对未来的代码编写做出了一些改变：

1. 将宏用 do {} while(0) 包裹，同时在调用宏的时候在末尾加上分号
2. 将一些能封装为函数的宏封装为函数
3. 加入了.clang-format，以后的代码可能都使用其进行格式化

**Comment by min0911Y** [comment]
臣附议
