### ISSUE TITLE
> > > > issue #7 似乎被意外关闭

### ISSUE THREAD

**Issue by min0911Y** [CLimber-Rong/stamon#10]
> > > > issue #7 似乎被意外关闭
> > > 
> > > 
> > > 很明显这**不是意外**
> > 
> > 
> > 很明显这是意外
> 
> 我也是这么认为的，可能从是仓库的所有者手滑了

**您比仓库的所有者更了解Stamon？**

_Originally posted by @CLimber-Rong in https://github.com/CLimber-Rong/stamon/issues/8#issuecomment-2310091136_
           我比较了解仓库的所有者

**Comment by CLimber-Rong** [comment]
请您重视您的Issue标题。
