### ISSUE TITLE
Floating-Point Parsing Error

### ISSUE THREAD

**Issue by copi143** [CLimber-Rong/stamon#12]
I encountered an issue when running the following code on Stamon:

```stamon
import std;
println(1.0);
```

The expected output should be `1.000000`, but instead, Stamon prints `0.000000`.

However, when I modify the code to `println(123 + 1.0);`, the output is 123. I suspect that this issue is caused by an error in parsing floating-point literals, where the value is incorrectly assigned as 0.

**Comment by CLimber-Rong** [comment]
看不懂，**您是中国人，想必会说中文**。

**Comment by CLimber-Rong** [comment]
您好，感谢您的报告！

这个漏洞真实存在，简单来说就是读写时大小端混乱，而且错用int存储double导致精度丢失。

目前该漏洞已经修复，您将会在接下来的发布中看到它！
