### ISSUE TITLE
Integer Parsing Error

### ISSUE THREAD

**Issue by copi143** [CLimber-Rong/stamon#13]
When I run the following code:

```stamon
import std;
println(10000000000000000000);
```

It outputs `-1981284352` as expected, similar to the behavior in C. However, when I add one more zero to the number:

```stamon
import std;
println(100000000000000000000);
```

It outputs `-1`, which is unexpected. The expected output is `1661992960`.

It seems like there is a problem with parsing large integer literals. I suggest either supporting the parsing of long numeric literals or, like Clang, throwing an error such as `error: integer literal is too large to be represented in any integer type`.

Thank you!

**Comment by Cassian824** [comment]
It seems that this issue can be addressed with a simple adjustment to the lexer. The recommended approach is to check the size of integers as they are processed, and immediately report an error if a value exceeds the allowed range. This will effectively prevent problems caused by integer overflow.

**Comment by Cassian824** [comment]
Another option is to define custom integer types that support big integers, similar to what is available in Python.

**Comment by CLimber-Rong** [comment]
您好！感谢您的报告！

我已经特殊判断了“数值过大”的情况，如果出现数值过大的字面量，我将会正常编译（但是生成的实际数值会与代码数值不同）并抛出编译警告。用户可以根据编译参数来决定是否忽略这些警告，或者将警告提升为致命错误。

目前该漏洞已经修复，您将会在接下来的发行版中看到它！
