### ISSUE TITLE
公示VM性能

### ISSUE THREAD

**Issue by min0911Y** [CLimber-Rong/stamon#7]
能否在之后的commit中加入一些benchmark的结果？

以及与其他编程语言的对比图

此致

&emsp;&emsp;敬礼

**Comment by CLimber-Rong** [comment]
**您可以自行完成！**

**Comment by min0911Y** [comment]
为什么

**Comment by min0911Y** [comment]
> **您可以自行完成！**

我可以帮你测试一下提一个PR吗

**Comment by wuyukai0403** [comment]
**冒泡**是意见重要的事情

**Comment by min0911Y** [comment]
我现在已经知道stamon的最新版本如下代码需要25s
```rust
import std;
def a = 0;

while(a < 100000) {
    println(a);
    a += 1;
}
```

**Comment by CLimber-Rong** [comment]
> > **您可以自行完成！**
> 
> 我可以帮你测试一下提一个PR吗

**不建议**，因为在我的规划里，Stamon的虚拟机将要进行重构，到时候很多习以为常的事情都会改变。显然这种测试的时效很短。

**Comment by CLimber-Rong** [comment]
> 我现在已经知道stamon的最新版本如下代码需要25s

已阅。

**Comment by min0911Y** [comment]
> > > **您可以自行完成！**
> > 
> > 
> > 我可以帮你测试一下提一个PR吗
> 
> **不建议**，因为在我的规划里，Stamon的虚拟机将要进行重构，到时候很多习以为常的事情都会改变。显然这种测试的时效很短。

可以加入JIT来优化性能吗？

**Comment by min0911Y** [comment]
> > > **您可以自行完成！**
> > 
> > 
> > 我可以帮你测试一下提一个PR吗
> 
> **不建议**，因为在我的规划里，Stamon的虚拟机将要进行重构，到时候很多习以为常的事情都会改变。显然这种测试的时效很短。

那就你每一个版本我都测试一次

**Comment by CLimber-Rong** [comment]
> 可以加入JIT来优化性能吗？

鉴于当前的能力，这是后话了。

**Comment by min0911Y** [comment]
**一个好的benchmark**是**一个好的编程语言的评判标准**

**Comment by CLimber-Rong** [comment]
> **一个好的benchmark**是**一个好的编程语言的评判标准**

已阅。
