### ISSUE TITLE
issue #7 似乎被意外关闭

### ISSUE THREAD

**Issue by copi143** [CLimber-Rong/stamon#8]
issue #7 似乎被意外关闭

**Comment by CLimber-Rong** [comment]
> issue #7 似乎被意外关闭

很明显这**不是意外**

**Comment by copi143** [comment]
> > issue #7 似乎被意外关闭
> 
> 很明显这**不是意外**

很明显这是意外

**Comment by min0911Y** [comment]
> > > issue #7 似乎被意外关闭
> > 
> > 
> > 很明显这**不是意外**
> 
> 很明显这是意外

我也是这么认为的，可能从是仓库的所有者手滑了

**Comment by CLimber-Rong** [comment]
> > > > issue #7 似乎被意外关闭
> > > 
> > > 
> > > 很明显这**不是意外**
> > 
> > 
> > 很明显这是意外
> 
> 我也是这么认为的，可能从是仓库的所有者手滑了

**您比仓库的所有者更了解Stamon？**
