### ISSUE TITLE
没有环境变量STAMON时无法运行

### ISSUE THREAD

**Issue by copi143** [CLimber-Rong/stamon#9]
没有环境变量STAMON时无法运行

是否应该支持获取程序所在的目录

**Comment by CLimber-Rong** [comment]
> 没有环境变量STAMON时无法运行
> 
> 是否应该支持获取程序所在的目录

我其实有思考过这个问题——这个问题过于依赖平台了。
我封装了``getenv``函数，如果您并不支持环境变量，可以自行更改路径获取方式。

``getenv``函数被封装到``stdlib.h``，基于标准C，更加的通用。

当然，如果您有更好的建议，欢迎提出！

以上，谢谢！

**Comment by min0911Y** [comment]
> > 没有环境变量STAMON时无法运行
> > 是否应该支持获取程序所在的目录
> 
> 我其实有思考过这个问题——这个问题过于依赖平台了。 我封装了`getenv`函数，如果您并不支持环境变量，可以自行更改路径获取方式。
> 
> `getenv`函数被封装到`stdlib.h`，基于标准C，更加的通用。
> 
> 当然，如果您有更好的建议，欢迎提出！
> 
> 以上，谢谢！

注意到您的Main.cpp文件中有这样一个东西：
```c
/*
	Name: Main.cpp
	Copyright: Apache 2.0
	Author: CLimber-Rong
	Date: 24/02/24 11:59
	Description:
    * 命令行工具
    * 该文件并不属于编译器或虚拟机的范畴，所以使用了平台库
    * 开发者可以自行更改或者建立属于自己的命令行工具
	* 在使用stamon之前，你需要配置环境变量
	* 即：将可执行文件所在目录设为STAMON
*/
```
那么既然如此是否应该将
```c
文件并不属于编译器或虚拟机的范畴，所以使用了平台库
```
剔除呢？

**Comment by CLimber-Rong** [comment]
> > > 没有环境变量STAMON时无法运行
> > > 是否应该支持获取程序所在的目录
> > 
> > 
> > 我其实有思考过这个问题——这个问题过于依赖平台了。 我封装了`getenv`函数，如果您并不支持环境变量，可以自行更改路径获取方式。
> > `getenv`函数被封装到`stdlib.h`，基于标准C，更加的通用。
> > 当然，如果您有更好的建议，欢迎提出！
> > 以上，谢谢！
> 
> 注意到您的Main.cpp文件中有这样一个东西：
> 
> ```c
> /*
> 	Name: Main.cpp
> 	Copyright: Apache 2.0
> 	Author: CLimber-Rong
> 	Date: 24/02/24 11:59
> 	Description:
>     * 命令行工具
>     * 该文件并不属于编译器或虚拟机的范畴，所以使用了平台库
>     * 开发者可以自行更改或者建立属于自己的命令行工具
> 	* 在使用stamon之前，你需要配置环境变量
> 	* 即：将可执行文件所在目录设为STAMON
> */
> ```
> 
> 那么既然如此是否应该将
> 
> ```c
> 文件并不属于编译器或虚拟机的范畴，所以使用了平台库
> ```
> 
> 剔除呢？

已修改为：
``文件并不属于编译器或虚拟机的范畴，所以使用了C标准库``

命令行工具完全不使用C标准库显然是异想天开的，所以我选择使用C标准库。

**Comment by CLimber-Rong** [comment]
我将会在**后续**把这些瑕疵统一修复并push。

**Comment by min0911Y** [comment]
> > > > 没有环境变量STAMON时无法运行
> > > > 是否应该支持获取程序所在的目录
> > > 
> > > 
> > > 我其实有思考过这个问题——这个问题过于依赖平台了。 我封装了`getenv`函数，如果您并不支持环境变量，可以自行更改路径获取方式。
> > > `getenv`函数被封装到`stdlib.h`，基于标准C，更加的通用。
> > > 当然，如果您有更好的建议，欢迎提出！
> > > 以上，谢谢！
> > 
> > 
> > 注意到您的Main.cpp文件中有这样一个东西：
> > ```c
> > /*
> > 	Name: Main.cpp
> > 	Copyright: Apache 2.0
> > 	Author: CLimber-Rong
> > 	Date: 24/02/24 11:59
> > 	Description:
> >     * 命令行工具
> >     * 该文件并不属于编译器或虚拟机的范畴，所以使用了平台库
> >     * 开发者可以自行更改或者建立属于自己的命令行工具
> > 	* 在使用stamon之前，你需要配置环境变量
> > 	* 即：将可执行文件所在目录设为STAMON
> > */
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 那么既然如此是否应该将
> > ```c
> > 文件并不属于编译器或虚拟机的范畴，所以使用了平台库
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 剔除呢？
> 
> 已修改为： `文件并不属于编译器或虚拟机的范畴，所以使用了C标准库`
> 
> 命令行工具完全不使用C标准库显然是异想天开的，所以我选择使用C标准库。

应当剔除，因为你的假设便是每个机器都有C标准库，那么便没有必要**强调**这一东西。

**Comment by CLimber-Rong** [comment]
> 应当剔除，因为你的假设便是每个机器都有C标准库，那么便没有必要强调这一东西。

依赖库位于``src/include``中，其中的``template``目录是依赖库的模板（即接口定义），如果你想要移植Stamon，只需要实现``template``目录中定义的接口即可。

为了示范，我将接口用C语言的标准库实现了一遍，并把代码放到``stdc_implemented``中。

如果你所在的平台支持C语言的标准库（具体标准为C89），那么可以直接使用``stdc_implemented``作为依赖库。

> ——摘自``工作日志20230131.md``

显然Stamon做了足够的封装，您**并不一定需要**实现C标准库。

但是命令行工具使用了，因此我要强调，以免出现不可控的情况。

我也**从来没有**假设过每个机器都有C标准库，您可以尝试**充分**地阅读文档。阅读文档往往比学习开发和提issue更管用。

**Comment by min0911Y** [comment]
> Referenc

另：增加可移植性的办法并不只有不使用任何平台库，好的抽象层也受到移植者的亲睐。

nasm的源代码便是一个例子，有些可有可无的功能，有了程序可以更漂亮，更好用，同样，这些功能可以dummy掉，这是业界的主流做法，希望您能参考。

**Comment by min0911Y** [comment]
我类比一些 SDL2库 有audio 输入法等模块   但是 他这些功能是可选的 可以dummy掉

**Comment by min0911Y** [comment]
应当使用 `config.h` 来配置功能

**Comment by min0911Y** [comment]
> 我类比一些 SDL2库 有audio 输入法等模块 但是 他这些功能是可选的 可以dummy掉

p.s: video模块也是可以dummy掉的

**Comment by CLimber-Rong** [comment]
> 我类比一些 SDL2库 有audio 输入法等模块 但是 他这些功能是可选的 可以dummy掉

Stamon也有类似地做法：https://github.com/CLimber-Rong/stamon2-portable

我已经对不同的命名空间做了隔离，见https://github.com/CLimber-Rong/stamon/issues/1

您可以根据需求使用不同的命名空间，引入不同的文件。

**Comment by CLimber-Rong** [comment]
显然当前话题已经超出“获取程序所在路径”所在的范围了，因此该issue被锁定。

您和我有其他的联系方式，显然利用其他方式联系是更方便的。

如果您是真心提建议的话，想必您会这么做。
